### ISSUE TITLE
Feil ved utlogging i demo

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/sso#115]
Det kan se ut som tokenet av og til ikke inneholder alt det skal. Timeout?
![image](https://user-images.githubusercontent.com/8625716/196424310-9ae9d9dd-7c75-46c8-842e-1f343a72ebb4.png)

Kan se ut som det kun gjelder fdk-registration-public klienten, men ikke verifisert

Bruker:

> jeg stod i oversiktsbildet for alle katalogene. Nå gjorde jeg nytt forsøk på å logge ut, og da gikk det greit
> 
> Jeg logget nettopp inn igjen og var da inne i datasettkatalogen i demo. Fikk samme feilmelding på nytt når jeg prøvde å logge ut. Jeg stod da inne i en datasettbeskrivelse når jeg prøvde å logge ut

**Comment by KjerstiSteien** [comment]
Er det mulig å bryte ned denne i mindre biter?

**Comment by valosnah** [comment]
Kanskje, men pdd er det vel litt uklart nøyaktig hva som er galt.
Trenger mer undersøkelser.

Logget litt inn og ut av demo med forskjellige brukere i demo ifm noe annet nå, og opplevde dette flere ganger, men fikk ikke helt konsekvent reprodusert det.

Jeg mistenker iallefall at dette problemet kun er knyttet til de som relativt hyppig logger inn og ut med forskjellige brukere.

**Comment by KjerstiSteien** [comment]
Kanskje vi i første omgang kan lage et issue for å reprodusere og beskrive feilen og timeboxe denne til x antall timer?

**Comment by jeffreiffers** [comment]
@valosnah Tror denne kan lukkes. Mener du løste det par uker siden.

**Comment by KjerstiSteien** [comment]
Klarer ikke å gjenskape. Lukker saken.
