### ISSUE TITLE
Sette opp innlogging for virksomhetene ved virksomhetenes interne AD

### ISSUE THREAD

**Issue by terjesyl** [Informasjonsforvaltning/sso#122]
**Brreg**
- [x] staging/demo
- [ ] prod 

**Skatt**
- [x] staging/demo
- [x] prod

**Comment by terjesyl** [comment]
Duplikat av #125 ?

**Comment by valosnah** [comment]
@terjesyl Nei, #125 er frontenden

**Comment by valosnah** [comment]
Mottatt relevant info fra IAM-admin i Skatt, lagt inn som providers i staging/demo og prod

**Comment by terjesyl** [comment]
Denne er fikset nå eller? @valosnah
