### ISSUE TITLE
Demo: Plutselig innlogget som annen bruker

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/sso#123]
Merk at det ikke er snakk om man blir logget inn som tilfeldig bruker, dette ser ut til å være knyttet til en sesjon som ikke blir skikkelig slettet fra nettleseren. Man får heller ikke tilgang til noe data.

Feilen er sannsynligvis i behandlingsoversikt (records-of-processing).

Hvordan reprodusere:
- Logg inn med en demobruker
- Gå inn i behandlingsoversikt
- Gå tilbake til hovedoversikten
- Logg ut
- Logg inn med ny bruker
- Åpne behandlingsoversikt
- Du er nå logget inn som den første brukeren

**Comment by NilsOveTen** [comment]
løst av https://github.com/Informasjonsforvaltning/catalog-frontend/commit/36fba3d02ed7f760109a31569924407d33d0c3fc
