### ISSUE TITLE
Fjern importering av theme fra keycloak versjon 16

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/sso#126]
Måten login-sidene blir tematisert på ble deprekert og så fjernet, dette blir ignorert og lastet inn fra keycloak 16 i Dockerfile for sso. Vi bør fjerne denne importeringen og legge til tematisering som støttes av nyere keycloak

**Comment by KurtStian** [comment]
Relatert: #135

**Comment by NilsOveTen** [comment]
løst av https://github.com/Informasjonsforvaltning/sso/pull/137
