### ISSUE TITLE
Bytte til Felles brukerhåndtering

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/sso#20]

**Comment by lillelars** [comment]
@joebrreg Dette kan du nå teste i staging ved å legge til orgnr for ramsund og rognan:
![image](https://user-images.githubusercontent.com/39513382/80586507-58fad000-8a15-11ea-89f1-5e2b1c7343e1.png)

**Comment by joebrreg** [comment]
@lillelars Fikk det til, men fortsatt noen issues igjen her, eller?
