### ISSUE TITLE
Utfasing av postgresql (SSO)

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/sso#65]
Postgresql kan fases helt ut hvis SSO fjerner avhengigheten sin av den.
Dette vil medføre en betydelig besparelse av månedlige kostnader.

**Comment by stigbd** [comment]
Avhengighet som i bruker den? Kva er i så fall alternativet?

**Comment by valosnah** [comment]
SSO bruker den ikke, den er bare avhengig at den eksisterer på oppstart.

**Comment by stigbd** [comment]
Då tenker eg at det berre er å fjerne. Går ut i frå at @NilsOveTen bekrefter dette.

**Comment by NilsOveTen** [comment]
Både ja og nei :P
Er jo bare å fjerne, problemet er at vi må fikle en god del med sso for at den ikke skal kreve at postgres er tilgjengelig.

**Comment by stigbd** [comment]
"Fikle" som i lage custom kode, eller "fikle" som i _fjerne_ custom code?

**Comment by NilsOveTen** [comment]
Eeh, ja, si det. Begge deler?
Tror default er at den krever postgres, men markko fikk den til å bruke en lokal "in-memory"-database i stedet. Vi la la til at den skulle bruke postgres når vi opprettet epost-brukere.
Så vi fjerner alt som har med epost-brukere å gjøre og legger til config for at den ikke skal bruke postgres.
-> Fjerne: Mye, Legge til: Litt

**Comment by valosnah** [comment]
Se gjerne på denne samtidig: Informasjonsforvaltning/sso#64

**Comment by valosnah** [comment]
Siden vi nå bruker postgresql igjen ifbm fdk-cms-service, er det ikke lenger ønskelig å fase ut.

**Comment by valosnah** [comment]
Dog, det hadde fortsatt vært greit om SSO fjernet avhengigheten sin av postgresql

**Comment by jeffreiffers** [comment]
Keycloak kommer standard med H2 database. Tror vi kan bare endre DB_VENDOR til H2 og fjerne alle andre env vars i gcp.

**Comment by valosnah** [comment]
Endret på konfig slik Jeff har foreslått, og SSO starter nå opp med H2.
Testet i staging ved å skru av postgresql-proxy

**Comment by shenluna** [comment]
Verifisert av Hans Olav
